import requests
import streamlit as st

st.set_page_config(layout="wide")
st.title("Camera input demo app. Take photo and see your caricature")

col_left, _, col_right = st.columns([5, 1, 4])


def camera_input_on_change():
    with col_right:
        if st.session_state.camerainputfirst:
            with st.spinner("Processing..."):
                r = requests.post(
                    "https://api.deepai.org/api/toonify",
                    files={"image": st.session_state.camerainputfirst},
                    headers={"api-key": st.secrets.api_key},
                )
                response = r.json()
                st.text("")
                st.text("")
                st.image(response["output_url"])
                st.caption(
                    "Image generated by [Toonify](https://deepai.org/machine-learning-model/toonify)"
                )


with col_left:
    st.camera_input(label="", key="camerainputfirst", on_change=camera_input_on_change)
